services:
    amex_web:
        build: .
        restart: always
        command: gunicorn --bind :8000 --workers 2 AMEX.wsgi
        volumes:
            - .:/AMEX
        ports:
            - 8000:8000
        environment:
            - DB_NAME=postgres
            - DB_USERNAME=username
            - DB_PASSWORD=password
            - DB_HOST=amex_db
            - DB_PORT=5432
        depends_on:
            - amex_db
    amex_db:
        image: postgres:14.0
        restart: always
        volumes:
            - pg_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=username
            - POSTGRES_PASSWORD=password
            - POSTGRES_HOST=db
        ports:
            - 5432:5432
    redis:
        container_name: amex_map_redis_container
        image: redis:latest
        restart: always
    celery_worker:
        build: .
        command: celery -A AMEX.celery worker --pool=solo -l info
        environment:
            - CELERY_BROKER_URL=redis://redis:6379
            - CELERY_RESULT_BACKEND=redis://redis:6379
            - DB_NAME=postgres
            - DB_USERNAME=username
            - DB_PASSWORD=password
            - DB_HOST=amex_db
            - DB_PORT=5432
        depends_on:
            - redis
            - amex_db
volumes:
    pg_data: