# Generated by Django 4.1.3 on 2022-12-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountdata',
            name='google_map_url',
            field=models.CharField(max_length=99999, null=True),
        ),
    ]
