# Generated by Django 4.1.3 on 2022-12-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_discountdata_google_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountdata',
            name='card_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='discountdata',
            name='card_name',
            field=models.CharField(max_length=99999, null=True),
        ),
    ]
