# Generated by Django 4.1.3 on 2022-12-02 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_discountdata_card_id_discountdata_card_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountdata',
            old_name='card_id',
            new_name='card',
        ),
    ]
