# Generated by Django 4.1.3 on 2022-12-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_rename_card_id_discountdata_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountdata',
            name='address',
            field=models.CharField(blank=True, max_length=99999, null=True),
        ),
        migrations.AlterField(
            model_name='discountdata',
            name='google_map_url',
            field=models.CharField(blank=True, max_length=99999, null=True),
        ),
        migrations.AlterField(
            model_name='discountdata',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discountdata',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discountdata',
            name='phone',
            field=models.CharField(blank=True, max_length=99999, null=True),
        ),
        migrations.AlterField(
            model_name='discountdata',
            name='place_web_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
