# Generated by Django 4.1.3 on 2023-01-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0005_alter_discountdata_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountdata",
            name="card_english_name",
            field=models.CharField(max_length=99999, null=True),
        ),
        migrations.AddField(
            model_name="discountdata",
            name="discount_description",
            field=models.CharField(max_length=99999, null=True),
        ),
        migrations.AddField(
            model_name="discountdata",
            name="reserve_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
